version: '3.9'

services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    volumes:
      - /psql_data/:/var/lib/postgresql/data
    env_file:
      - .env

  webapp:
    build: .
    restart: always
    container_name: tech_shop
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 8000:8000
    command: >
      bash -c "python ./src/manage.py migrate && python src/manage.py loaddata src/fixtures/db.json && python ./src/manage.py runserver 0.0.0.0:8000"

  stripe-cli:
    image: stripe/stripe-cli
    restart: always
    depends_on:
      - webapp
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to webapp:8000/orders/stripe-webhook/"
    env_file:
      - .env

  worker:
    build: .
    restart: always
    depends_on:
      - webapp
    command: >
      bash -c "celery --workdir=./src -A tech_shop worker"