version: '3.9'

services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    volumes:
      - C:\Users\dima3\OneDrive\Робочий стіл\psql_docker:/var/lib/postgresql/data
    env_file:
      - .env

  webapp:
    build: .
    restart: always
    container_name: tech_shop
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 8000:8000
    command: >
      bash -c "python ./src/manage.py migrate && python src/manage.py loaddata --exclude auth.permission --exclude contenttypes src/fixtures/data.json && python ./src/manage.py runserver 0.0.0.0:8000"