# Generated by Django 4.2.8 on 2024-01-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='storage_amount',
            new_name='storage_quantity',
        ),
    ]
