# Generated by Django 4.2.8 on 2024-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('OP', 'В обробці'), ('PP', 'Готується до відправлення'), ('GT', 'Прямує до замовника'), ('AR', 'Прибуло до відділення'), ('WP', 'Очікується оплата'), ('WS', 'Очікує на складі'), ('OC', 'Замовлення відмінено'), ('DN', 'Виконано')], default='OP', max_length=2, verbose_name='Статус замовлення'),
        ),
    ]
